[versions]
ktlint = "0.49.1"
serialize = "1.5.1"
xml = "0.86.1"

[plugins]
spotless = "com.diffplug.spotless:6.20.0"

[libraries]
serialize-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialize" }
serialize-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialize" }
codebook = "io.papermc.codebook:codebook:1.0.1"
diffutils = "io.github.java-diff-utils:java-diff-utils:4.12"
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.2"
jgit = "org.eclipse.jgit:org.eclipse.jgit:6.6.0.202305301015-r"

xml-core = { module = "io.github.pdvrieze.xmlutil:core-jvm", version.ref = "xml" }
xml-serialize = { module = "io.github.pdvrieze.xmlutil:serialization-jvm", version.ref = "xml" }
